"""empty message

Revision ID: 651d5e552f47
Revises: 948e1d8dae5e
Create Date: 2019-07-21 16:59:06.766207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651d5e552f47'
down_revision = '948e1d8dae5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
