version: "3"

volumes:
  flask_blog.db:
    external: true

services:
  database:
    container_name: flask_blog.db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - flask_blog.db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Katerina
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: flask_blog
