"""empty message

Revision ID: 865974ec076f
Revises: 2f0190442dbd
Create Date: 2019-09-12 17:25:23.777697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865974ec076f'
down_revision = '2f0190442dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
