"""empty message

Revision ID: 527f4a87fb0a
Revises: 3e8df3b6b947
Create Date: 2019-09-20 14:40:52.740758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '527f4a87fb0a'
down_revision = '3e8df3b6b947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_message_created'), 'message', ['created'], unique=False)
    op.drop_index('ix_message_timestamp', table_name='message')
    op.drop_column('message', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_message_timestamp', 'message', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_message_created'), table_name='message')
    op.drop_column('message', 'created')
    # ### end Alembic commands ###
