"""empty message

Revision ID: 95364e268593
Revises: e16b587eb41d
Create Date: 2019-09-11 15:54:56.138332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95364e268593'
down_revision = 'e16b587eb41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
